- name: Enable pcscd
  become: yes
  service: name=pcscd state=started
  when: ansible_distribution == "Fedora" or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Enable pcscd
  become: yes
  service: name=pcscd enabled=no
  when: ansible_distribution == "Fedora" or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
