- stat: path=/sssd/contrib/sssd.spec.in
  register: st

- name: Install sssd build dependencies
  become: yes
  command: yum-builddep -y sssd
  when: st.stat.exists and ansible_distribution == "CentOS"

- name: Make sure dnf plugins are installed
  become: yes
  command: dnf -y upgrade python3-dnf-plugins-core
  when: st.stat.exists and ansible_distribution == "Fedora"

- name: Install sssd build dependencies
  become: yes
  command: dnf builddep -y sssd
  when: st.stat.exists and ansible_distribution == "Fedora"
