- name: Install freeipa-client
  dnf: pkg=freeipa-client state=installed
  when: ansible_distribution == "Fedora"

- name: Install ipa-client
  dnf: pkg=ipa-client state=installed
  when: ansible_distribution == "CentOS"
