
- name: Allow access from our network
  win_firewall_rule:
      name: Allow access from our network
      direction: in
      action: allow
      enabled: yes
      state: present

- name: Install Active Directory Services
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present

- name: Install DNS
  win_feature:
    name: DNS
    include_management_tools: yes
    include_sub_features: yes
    state: present
