- name: Stop firewalld
  service: name=firewalld state=stopped
  become: True
  when: ansible_distribution == "Fedora" or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Disable firewalld
  service: name=firewalld enabled=no
  become: True
  when: ansible_distribution == "Fedora" or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Stop firewalld
  become: True
  service: name=iptables state=stopped
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or
        (ansible_distribution == "CentOS" and ansible_distribution_major_version == "5")

- name: Disable firewalld
  become: True
  service: name=iptables enabled=no
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or
        (ansible_distribution == "CentOS" and ansible_distribution_major_version == "5")
