- name: install git and hub
  become: yes
  tags:
    - packages
  package:
    name: ['git', 'hub', 'tig']
    state: latest

- name: Template .gitconfig
  become: yes
  template:
    src: gitconfig.template
    dest: "{{ homedir }}/.gitconfig"

