- include: useradd.yml
- include: sudo.yml
- include: git.yml
- include: zsh.yml
- include: tmux.yml
- include: vim.yml

- name: Template authorized_keys
  become: yes
  template:
    src=authorized_keys
    dest=/home/jhrozek/.ssh/authorized_keys
