- name: install tmux
  become: yes
  tags:
    - packages
  package:
    name: tmux
    state: latest

- name: Clone TPM
  become: yes
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ homedir }}/.tmux/plugins/tpm"

- name: Template .tmux.conf
  become: yes
  template:
    src: tmux.conf.template
    dest: "{{ homedir }}/.tmux.conf"
