- name: install and configure git
  become: yes
  tags:
    - packages
  package:
    name: vim-enhanced
    state: latest

- name: Clone Vundle
  become: yes
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: "{{ homedir }}/.vim/bundle/Vundle.vim"

- name: Template .vimrc
  become: yes
  template:
    src: vimrc.template
    dest: "{{ homedir }}/.vimrc"
