- name: Remove hostname from /etc/hosts
  become: True
  lineinfile:
    path: /etc/hosts
    regexp: '^(127\.0\.0\.1|::1)[ \t]+{{ server_fqdn }}.*$'
    state: absent

- name: Install IPA server
  become: True
  shell: |
    /usr/sbin/ipa-server-install --unattended          \
      --realm={{ ipa_domain | upper | quote }}         \
      --domain={{ ipa_domain | quote }}                \
      --ds-password={{ ipa_password | quote }}         \
      --admin-password={{ ipa_password | quote }}      \
      --hostname={{ server_fqdn | quote }}             \
      --setup-dns                                      \
      --auto-forwarders                                \
      --auto-reverse                                   \
      --no-dnssec-validation                           \
      --no-host-dns
  register: ipa_installation
  args:
    creates: /etc/ipa/default.conf

- name: Remove vagrant DNS A records
  shell: |
    echo {{ ipa_password | quote }} | kinit admin

    ipa dnsrecord-show {{ item.zone | quote }} {{ item.name | quote }} | grep {{ item.ip | quote }}
    if [ $? -ne 0 ]; then
      echo "Record {{ item.ip | quote }} in {{ item.name | quote }}.{{ item.zone | quote }} is not present. Nothing to do."
      exit 255
    fi

    ipa dnsrecord-del {{ item.zone | quote }} {{ item.name | quote }} \
      --a-rec={{ item.ip | quote }}
  register: result
  failed_when: "result.rc != 255 and result.rc != 0"
  changed_when: "result.rc == 0"
  with_items:
  - { zone: '{{ ipa_domain }}', name: 'ipa-ca', ip: '{{ ansible_default_ipv4.address }}'}
  - { zone: '{{ ipa_domain }}', name: '{{ server_shortname }}', ip: '{{ ansible_default_ipv4.address }}'}

