---
- name: install and provision IPA trust server
  hosts: ipa_trust_server
  become: True

  roles:
      - { role: common, tags: ['common'] }
      - { role: jhrozek, tags: ['jhrozek'] }
      - { role: ipaserver, tags: ['ipaserver'] }
      - { role: sssd_devel, tags: ['sssd_devel'] }

- name: install and provision IPA trust client
  hosts: ipa_trust_client
  become: True

  roles:
      - { role: common, tags: ['common'] }
      - { role: jhrozek, tags: ['jhrozek'] }
      - { role: ipaclient, tags: ['ipaclient'] }
      - { role: sssd_devel, tags: ['sssd_devel'] }

- name: install and provision AD forest root
  hosts: ad_dc

  roles:
      - { role: ad_common, tags: ['ad_common'] }
      - { role: ad_forest, tags: ['ad_forest'] }
